import QRCode from "qrcode";
import { restaurantUrl, restaurantWhatsAppUrl } from "@/lib/utils/site";
import { ShareActions } from "@/components/restaurant/ShareActions";

// Shows a restaurant's ordering link and QR code, with copy / download buttons.
// The QR is drawn on the server as SVG, so nothing extra is loaded in the browser.
export async function ShareCard({ name, slug }: { name: string; slug: string }) {
  const url = restaurantUrl(slug);
  const svg = await QRCode.toString(url, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 2,
    width: 320,
    color: { dark: "#000000", light: "#ffffff" },
  });

  return (
    <section className="flex flex-col gap-4 rounded-2xl border border-border bg-surface p-4 shadow-sm">
      <div>
        <h2 className="text-lg font-semibold">Share your ordering link</h2>
        <p className="text-sm text-stone-600">
          Customers who open this link or scan the QR code land straight on {name}&apos;s menu.
          Put it on your Instagram, WhatsApp status, menu cards or the counter.
        </p>
      </div>

      <div className="flex flex-col items-center gap-4 sm:flex-row sm:items-start">
        {/* The QR is generated by our own code above, not user input. */}
        <div
          role="img"
          aria-label={`QR code for ${name}`}
          className="size-40 shrink-0 overflow-hidden rounded-xl border border-border bg-white [&>svg]:size-full"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <ShareActions url={url} name={name} slug={slug} whatsappUrl={restaurantWhatsAppUrl(slug)} />
      </div>
    </section>
  );
}
